# Generated by Django 5.1.6 on 2025-02-13 19:08

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(default="sin descripcion"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="image",
            field=models.ImageField(
                blank=True,
                default="productos_img/no_image.jpg",
                null=True,
                upload_to=apps.productos.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
