# Generated by Django 5.1.6 on 2025-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_remove_producto_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
