# Generated by Django 5.1.6 on 2025-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
