# Generated by Django 5.1.6 on 2025-02-23 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_producto_marca_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_categoria", models.CharField(max_length=255, unique=True)),
                ("descripcion_categoria", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.categoria",
                to_field="nombre_categoria",
            ),
        ),
    ]
