# Generated by Django 5.1.6 on 2025-02-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_categoria_producto_categoria"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Categorias",
        ),
    ]
