# Generated by Django 5.1.6 on 2025-02-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_remove_producto_categoria_delete_categorias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_categoria", models.CharField(max_length=255, unique=True)),
                ("descripcion_categoria", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
