# Generated by Django 5.1.6 on 2025-02-23 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0008_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productos.categoria",
            ),
        ),
    ]
