# Generated by Django 5.1.6 on 2025-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0011_producto_codigo_qr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="codigo_qr",
        ),
    ]
