# Generated by Django 5.1.6 on 2025-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0012_remove_producto_codigo_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_qr",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
