# Generated by Django 5.1.6 on 2025-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0014_producto_costo_producto_descuento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suministradores",
            fields=[
                ("provedor_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_proveedor", models.CharField(max_length=255, unique=True)),
                ("contacto", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
