# Generated by Django 5.1.6 on 2025-03-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0015_suministradores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suministradores",
            options={
                "verbose_name": "Suministrador",
                "verbose_name_plural": "Suministradores",
            },
        ),
        migrations.RemoveField(
            model_name="suministradores",
            name="contacto",
        ),
    ]
