# Generated by Django 5.1.6 on 2025-03-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0016_alter_suministradores_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suministradores",
            name="email",
            field=models.EmailField(default="rijo@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="suministradores",
            name="telefono",
            field=models.CharField(default="12345", max_length=20),
            preserve_default=False,
        ),
    ]
