# Generated by Django 5.1.6 on 2025-03-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0018_alter_suministradores_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="suministrador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="productos.suministradores",
            ),
            preserve_default=False,
        ),
    ]
