# Generated by Django 5.1.6 on 2025-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0020_movimientoproducto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientoproducto",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA", "Salida"),
                    ("ACTUALIZACION", "Actualización"),
                    ("CREACION", "Creación"),
                ],
                max_length=20,
            ),
        ),
    ]
