# Generated by Django 5.1.6 on 2025-04-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0021_alter_movimientoproducto_tipo_movimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoproducto",
            name="ultima_alerta_stock",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
