# Generated by Django 5.1.6 on 2025-04-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0022_movimientoproducto_ultima_alerta_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimientoproducto",
            name="ultima_alerta_stock",
        ),
    ]
