# Generated by Django 5.1.6 on 2025-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0023_remove_movimientoproducto_ultima_alerta_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="ultima_alerta_stock",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
