# Generated by Django 5.1.6 on 2025-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cargo",
            field=models.CharField(
                choices=[("vendedor", "Vendedor"), ("cliente", "Cliente")],
                default="vendedor",
                max_length=10,
            ),
        ),
    ]
