# Generated by Django 5.1.6 on 2025-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("vendedor", "Vendedor"),
                    ("cliente", "Cliente"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=10,
            ),
        ),
    ]
