# Generated by Django 5.1.6 on 2025-02-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_cargo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="cargo",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_client",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
