# Generated by Django 5.1.6 on 2025-03-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_client",
        ),
    ]
