# Generated by Django 5.1.6 on 2025-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="impuesto",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
