# Generated by Django 5.1.6 on 2025-02-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_alter_detalleventa_subtotal_alter_venta_fecha_venta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("Efectivo", "Efectivo"),
                    ("Tarjeta", "Tarjeta"),
                    ("Transferencia", "Transferencia"),
                ],
                max_length=50,
            ),
        ),
    ]
