# Generated by Django 5.1.6 on 2025-02-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_alter_venta_metodo_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="empleado",
        ),
        migrations.DeleteModel(
            name="DetalleVenta",
        ),
        migrations.DeleteModel(
            name="Venta",
        ),
    ]
