# Generated by Django 5.1.6 on 2025-04-07 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0010_detalleventa_cantidad_descuento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        help_text="Ej: F-000001", max_length=20, unique=True
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura",
                        to="ventas.venta",
                    ),
                ),
            ],
        ),
    ]
